'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebBaixa.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3270() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3270", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property accessories_calculator() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("accessories_calculator", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property accessories_calculator_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("accessories_calculator_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property accessories_calculator_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accessories_calculator_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property accessories_calculator_5() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("accessories_calculator_5", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_exit_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_exit_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_vnd_ms_excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_vnd_ms_excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_vnd_ms_excel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_vnd_ms_excel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property application_x_compressed_tar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application_x_compressed_tar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appointment_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appointment_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property archive_insert_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("archive_insert_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property arrow_right_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_switch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_switch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arvore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arvore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aslfaltando() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aslfaltando", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property attach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockdevice_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockdevice_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blockdevice_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockdevice_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boleto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boleto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botton1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botton1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bradeira2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bradeira2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bradeira3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bradeira3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bradesco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bradesco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bradesco_banco_logo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bradesco_banco_logo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Brandeira() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brandeira", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnCancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnCancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnOk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnOk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnQuestion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnQuestion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btnWarning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnWarning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cadeado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cadeado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CartProt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CartProt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cat_22x22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cat_22x22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CodBarras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CodBarras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property code_class() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("code_class", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property code_class1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("code_class1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property completion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("completion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property computer_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property computer_laptop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_laptop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property computer_mainframe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_mainframe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property configure_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configure_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property confirmacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("confirmacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property correio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property correioDeletado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correioDeletado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property correioErro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("correioErro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete_table_row() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_table_row", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desistencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desistencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_cancel_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_cancel_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_cancel_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_cancel_41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_fewer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_fewer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_more() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_more", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_ok_apply_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_ok_apply_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_ok_apply_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_ok_apply_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property distribute_vertical_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("distribute_vertical_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draw_line_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draw_line_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DSPS140() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DSPS140", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_undo_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_undo_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_undo_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_undo_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Edita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_money_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_money_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_symbolic_link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_symbolic_link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_system_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_system_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emblem_system_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emblem_system_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Erro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property evento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("evento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye_of_gnome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye_of_gnome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ferramenta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ferramenta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property format_indent_more_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("format_indent_more_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property format_indent_more_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("format_indent_more_31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property format_list_unordered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("format_list_unordered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo_sobre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo_sobre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gerar_diferenca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gerar_diferenca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GFT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GFT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property globo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property help_faq() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("help_faq", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeBradesco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeBradesco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeConfig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeConfig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeDesligar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeDesligar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeEngrenagem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeEngrenagem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeEscritorios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeEscritorios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeImpressao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeImpressao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeLinha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeLinha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeLogout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeLogout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeMoedas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeMoedas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeMoedas2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeMoedas2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconePraca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconePraca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeReceber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeReceber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeTeclado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeTeclado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeUsers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeUsers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconeValidar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconeValidar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Imagem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Imagem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Import1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Import1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Import2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Import2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Impressora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Impressora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property insert_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insert_table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property insert_table_row() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insert_table_row", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property insert_table_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insert_table_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property justificar_um() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("justificar_um", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property justificar_varios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("justificar_varios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lifejacket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lifejacket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lockoverlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lockoverlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoBoleto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoBoleto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoBoleto2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoBoleto2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoIso9001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoIso9001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magic_tophat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magic_tophat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magic_tophat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magic_tophat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magica_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magica_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_unread() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_unread", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mail_unread_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_unread_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Menos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mini_erro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_erro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mini_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property moska() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moska", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property news_subscribe_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("news_subscribe_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property novo_editar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo_editar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property novo_excluir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo_excluir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property novo_incluir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo_incluir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property novo_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property novo_pesquisar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo_pesquisar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property novo_voltar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo_voltar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nucleo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nucleo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property object_locked_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("object_locked_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property onepixel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("onepixel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property params() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("params", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PeDeEfe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PeDeEfe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PeDeEfe2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PeDeEfe2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property preferences_system_network_2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("preferences_system_network_2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printer_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property proc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("proc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property proc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("proc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rede() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rede", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property remessa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remessa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property resp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property retorno() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("retorno", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property robo_bradesco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("robo_bradesco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property robo_bradesco2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("robo_bradesco2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seta_ant_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seta_ant_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seta_dir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seta_dir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seta_prox_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seta_prox_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property SMW() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SMW", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snes_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snes_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snes_controller2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snes_controller2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snes_controller3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snes_controller3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Somatoria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Somatoria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sonda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sonda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tools_wizard_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tools_wizard_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property top_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property top2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property user_home2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("user_home2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_sort_descending() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_sort_descending", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property voltar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voltar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property window_duplicate_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_duplicate_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property workf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("workf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property xls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property xrobo_bradesco2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xrobo_bradesco2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
